model: FDSA
dataset: tmall

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, category_id, seller_id, brand_id]

selected_features: [category_id, seller_id, brand_id]
normalize_all: True

hidden_size: 128 # embedding size

attn_dropout_prob: 0.2
hidden_dropout_prob: 0.2
learning_rate: 0.0005
n_heads: 1
n_layers: 2