model: GCSANGNN
dataset: tmall

data_path: "../data/"
additional_feat_suffix: [itememb]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    itememb: [iid, item_emb]

alias_of_item_id: [iid]
preload_weight:
    iid: item_emb

hidden_size: 128 # embedding size
inner_size: 256
n_layers: 1
n_heads: 1
hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02
step: 1
weight: 0.6
reg_weight: 5e-5
