model: GRU4Rec
dataset: tmall

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]

embedding_size: 128
hidden_size: 128
num_layers: 1
dropout_prob: 0.4
learning_rate: 0.005