model: GCSANF
dataset: diginetica

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, category_id, name_tokens, pricelog2]

selected_features: [category_id, pricelog2]
normalize_all: True
pooling_mode: sum

hidden_size: 128 # embedding size
inner_size: 256
n_layers: 1
n_heads: 1
hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02
step: 1
weight: 0.6
reg_weight: 5e-5
