model: NARM
dataset: diginetica

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, category_id, name_tokens, pricelog2]

embedding_size: 128
hidden_size: 128
n_layers: 1
learning_rate: 0.001
dropout_probs: [0.25,0.5]