model: SRGNN
dataset: diginetica

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, category_id, name_tokens, pricelog2]

embedding_size: 128
