model: FDSA
dataset: yoochoose-64

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, category_id]

selected_features: [category_id]
normalize_all: True

embedding_size: 128

attn_dropout_prob: 0.5
hidden_dropout_prob: 0.2
learning_rate: 0.0005
n_heads: 2
n_layers: 3