model: GRU4RecF
dataset: yoochoose-64

data_path: "../data/"

benchmark_filename: ['train', 'valid', 'test']

alias_of_item_id: [item_id_list]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp, item_id_list]
    item: [item_id, category_id]

selected_features: [category_id]
normalize_all: True

embedding_size: 128
hidden_size: 128
num_layers: 1

dropout_prob: 0.3
pooling_mode: sum

learning_rate: 0.005

