model: NextItNetGNN
dataset: yoochoose-64

data_path: "../data/"
additional_feat_suffix: [itememb]

benchmark_filename: ['train', 'valid', 'test']

alias_of_item_id: [item_id_list]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp, item_id_list]
    itememb: [iid, item_emb]

alias_of_item_id: [iid, item_id_list]
preload_weight:
    iid: item_emb

embedding_size: 128
kernel_size: 3
block_num: 5
dilations: [1,4]
reg_weight: 1e-5 