model: SASRec
dataset: yoochoose-64

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]

embedding_size: 128
hidden_size: 128

attn_dropout_prob: 0.2
hidden_dropout_prob: 0.2

n_heads: 1
n_layers: 3

learning_rate: 0.0001