model: VSKNN
dataset: yoochoose-64

data_path: "../data/"

benchmark_filename: ['train', 'valid', 'test']

alias_of_item_id: ['item_id_list']

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id_list, item_id, timestamp]

k: 1500
sample_size: 2500
sampling: recent

remind: True
extend: False

similarity: 'vec'
weighting: 'same'
dwelling_time: False
last_n_days: null
last_n_clicks: null
push_reminders: False
add_reminders: False
weighting_score: 'log'
weighting_time: False
normalize: True
idf_weighting: 1
idf_weighting_session: False

epochs: 1
