dataname: yoochoose-64
save_dir: 'data/'
epochs: 1000
patience: 20
transductive: False
emb_size: 128
gpu: 0
verbose: 1
batch_size: 512

saint_sampling: False
walk_length: 2
num_steps: 5

num_neighbors: [20,10]

drop_edge_p_1: 0.2
drop_edge_p_2: 0.2
drop_feat_p_1: 0.35
drop_feat_p_2: 0.3

encoder_dropout: 0.0
encoder_hidden_layer: 128
num_layers: 2
num_heads: 1
predictor_hidden_size: 512

lr: 1.0e-5
mm: 0.99
weight_decay: 1.0e-5