model: GRU4RecGNN
dataset: yoochoose-4

data_path: "../data/"
additional_feat_suffix: [itememb]

benchmark_filename: ['train', 'valid', 'test']


USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp, item_id_list]
    item: [item_id, category_id]
    itememb: [iid, item_emb]

alias_of_item_id: [iid, item_id_list]
preload_weight:
    iid: item_emb

embedding_size: 128 # must be equal to gnn emb size
hidden_size: 128
num_layers: 1

dropout_prob: 0.3
pooling_mode: sum



