model: Caser
dataset: music4all

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]

embedding_size: 128

nh: 16
nv: 8
MAX_ITEM_LIST_LENGTH: 10
reg_weight: 1e-5
dropout_prob: 0.5
learning_rate: 0.001

