model: LightGCNSeqF
dataset: music4all

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, popularity, release, danceability, energy, key, mode, valence, tempo, duration_ms, language, tags, ivec]

selected_features: [popularity, release, danceability, energy, key, mode, valence, tempo, duration_ms, language, tags, ivec]
normalize_all: True
pooling_mode: sum

embedding_size: 128

n_layers: 2
reg_weight: 1e-05

neg_sampling: {'uniform': 1}
loss_type: BPR

learning_rate: 0.0001


