model: SASRec
dataset: music4all

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]

hidden_size: 128 # embedding size

attn_dropout_prob: 0.5
hidden_dropout_prob: 0.5
learning_rate: 0.0001
n_heads: 2
n_layers: 2