model: SKNN
dataset: music4all

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]

k: 100
sample_size: 500
sampling: recent
remind: False
extend: False

normalize: True
similarity: 'jaccard'
pop_boost: 0

epochs: 1