model: STAMPGNN
dataset: music4all

data_path: "../data/"
additional_feat_suffix: [itememb]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    itememb: [iid, item_emb]

alias_of_item_id: [iid]
preload_weight:
    iid: item_emb

embedding_size: 128

learning_rate: 0.0005