model: GCSANF
dataset: mssd

data_path: "../data/"
benchmark_filename: ['train', 'valid', 'test']
alias_of_item_id: [item_id_list]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp, item_id_list]
    item: [item_id, duration, us_popularity_estimate, acousticness, beat_strength, bounciness, danceability,
           dyn_range_mean, flatness, instrumentalness, liveness, loudness, mechanism, organism, speechiness, tempo,
           valence, release_year, key, mode, time_signature, acoustic_vector]

selected_features: [us_popularity_estimate, acousticness, beat_strength, bounciness, danceability,
           dyn_range_mean, flatness, instrumentalness, liveness, loudness, mechanism, organism, speechiness, tempo,
           valence, release_year, key, mode, time_signature, acoustic_vector]
normalize_all: True
pooling_mode: sum

hidden_size: 128
inner_size: 256
n_layers: 1
n_heads: 1
hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02
step: 1
weight: 0.6
reg_weight: 5e-5
