model: GRU4RecF
dataset: mssd

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [ session_id, item_id, timestamp ]
    item: [ item_id, duration, us_popularity_estimate, acousticness, beat_strength, bounciness, danceability,
            dyn_range_mean, flatness, instrumentalness, liveness, loudness, mechanism, organism, speechiness, tempo,
            valence, release_year, key, mode, time_signature ]

selected_features: [ duration, us_popularity_estimate, acousticness, beat_strength, bounciness, danceability,
                     dyn_range_mean, flatness, instrumentalness, liveness, loudness, mechanism, organism, speechiness, tempo,
                     valence, release_year, key, mode, time_signature ]
normalize_all: True

embedding_size: 128
hidden_size: 128
num_layers: 1

dropout_prob: 0.4
pooling_mode: sum

learning_rate: 0.001
