model: LightGCNSeq
dataset: mssd

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]

embedding_size: 128

n_layers: 2
reg_weight: 1e-05

neg_sampling: {'uniform': 1}
loss_type: BPR

learning_rate: 0.001
