model: LightGCNSeqF
dataset: mssd

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    item: [item_id, duration, us_popularity_estimate, acousticness, beat_strength, bounciness, danceability,
           dyn_range_mean, flatness, instrumentalness, liveness, loudness, mechanism, organism, speechiness, tempo,
           valence, release_year, key, mode, time_signature]

selected_features: [duration, us_popularity_estimate, acousticness, beat_strength, bounciness, danceability,
           dyn_range_mean, flatness, instrumentalness, liveness, loudness, mechanism, organism, speechiness, tempo,
           valence, release_year, key, mode, time_signature]
normalize_all: True
pooling_mode: sum

embedding_size: 128

n_layers: 2
reg_weight: 1e-05

neg_sampling: {'uniform': 1}
loss_type: BPR

learning_rate: 0.001


