model: SKNNGNN
dataset: mssd

data_path: "../data/"
additional_feat_suffix: [itememb]

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]
    itememb: [ iid, item_emb ]

alias_of_item_id: [ iid ]
preload_weight:
    iid: item_emb

emb_threshold: 0.8

k: 100
sample_size: 1000
sampling: recent
remind: False
extend: False

normalize: True
similarity: 'jaccard'
pop_boost: 0

epochs: 1