model: VSTAN
dataset: mssd

data_path: "../data/"

USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
    inter: [session_id, item_id, timestamp]

k: 100
sample_size: 5000
sampling: recent
remind: True
extend: False
lambda_spw: 1.02
lambda_snh: 5
lambda_inh: 2.05

lambda_ipw: 1.02
lambda_idf: 5

epochs: 1